[package]
name = "turtle-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
censor = "0.3.0"
chrono = "0.4.30"
chrono-tz = "0.8.3"
config = "0.13.3"
dotenvy = "0.15.7"
once_cell = "1.18.0"
reqwest = { version = "0.11.20", features = ["blocking"] }
serde = "1.0.188"
serde-aux = "4.2.0"
teloxide = { version = "0.12.2", features = [
  "macros",
  "webhooks-axum",
  "webhooks",
] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = { version = "0.9.4", features = ["signal"] }
tracing = "0.1.37"
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
utoipa = { version = "3.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.5", features = ["axum"] }
