[package]
name = "turtle-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
censor = "0.3.0"
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
config = "0.13.3"
dotenvy = "0.15.7"
once_cell = "1.18.0"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = "1.0.188"
serde-aux = "4.2.0"
sqlx = { version = "0.7.2", default-features = false, features = [
  "macros",
  "postgres",
  "chrono",
  "migrate",
  "tls-native-tls",
] }
teloxide = { version = "0.12.2", features = [
  "macros",
  "webhooks-axum",
  "webhooks",
] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
tokio-cron-scheduler = { version = "0.9.4", features = ["signal"] }
tracing = "0.1.37"
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
utoipa = { version = "4.0.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }
uuid = { version = "1.4.1", features = ["v4"] }
