[workspace]
members = ["my_app", "my_bot", "my_server"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
chrono-tz = "0.9.0"
dotenvy = "0.15.7"
figment = { version = "0.10.17", features = ["yaml", "env"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
teloxide = { version = "0.12.2", features = ["macros", "webhooks", "webhooks-axum"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = { version = "0.10.0", features = ["signal"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18" }
uuid = { version = "1.8.0", features = ["v4"] }

[workspace.dependencies.sqlx]
version = "0.7.4"
default-features = false
features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "macros"]

[profile.dev]
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).

[profile.release]
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).
debug = 0

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
