[package]
name = "polarrbear-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
config = "0.13.3"
dotenv = "0.15.0"
serde = "1.0.188"
serde-aux = "4.2.0"
teloxide = { version = "0.12.2", features = ["macros", "webhooks-axum", "webhooks"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
utoipa = { version = "3.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.5", features = ["axum"] }
