# to simulate production runtime on localhost
services:
  telebot:
    image: telebot_image
    container_name: telebot_container
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      # these env keys have to be set for deployment.
      # the values used below are for production simulation purpose.
      # for more details, refer to `./.env.prod`.
      - APP_DATABASE__USERNAME=postgres
      - APP_DATABASE__PASSWORD=password
      - APP_DATABASE__HOST=database
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__REQUIRE_SSL=false # remove this env when in actual prod environment.
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: postgres_db_telebot
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=telebot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
#     volumes:
#       - postgres_data_stg:/var/lib/postgresql/data
#
# volumes:
#   postgres_data_stg:
