# docker to test out production environment works in local computer
services:
  telebot:
    image: turtlebot
    container_name: turtlybot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
