[package]
name = "turtle-bot"
version.workspace = true
edition.workspace = true

[dependencies]
async-openai = "0.21.0"
chrono = "0.4.38"
chrono-tz = "0.9.0"
teloxide = { version = "0.12.2", features = ["macros", "webhooks", "webhooks-axum"] }
tokio-cron-scheduler = { version = "0.10.0", features = ["signal"] }

anyhow.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
uuid.workspace = true
gaia = { version = "0.1.0", path = "../gaia" }
tokio.workspace = true

[lints]
workspace = true
