application:
  bot_port: 8443
  web_port: 5000
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  database_name: telebot
email:
  api: https://api.brevo.com/v3/smtp/email
